/**
 * Generated by make.sh file.
 * Just edit impl function
 * @copyright Copyright (c) 2025 jinho.choi
 * @see https://www.acmicpc.net/problem/9375
 * @license This code is for educational purposes only.
 */

#include <bits/stdc++.h>

using namespace std;

void impl() {
    int t;
    cin >> t;

    for (int i = 0; i < t; i++) {
        int n;
        cin >> n;
        
        map<string, int> v;

        for (int j = 0; j < n; j++) {
            string str1, str2;
            cin >> str1 >> str2;
            v[str2]++;
        }
        
        int result = 1;
        for (auto i : v) {
            result *= (i.second + 1);
        }
        cout << result - 1 << "\n";
    }
}

int main() {
    // This line is uncommented when starting process in local.
    // freopen("./questions/boj-9375.txt", "r", stdin);
    // for faster input/output
    ios_base::sync_with_stdio(false);cin.tie(NULL);cout.tie(NULL);

    impl();

    return 0;
}
