/**
 * Generated by make.sh file.
 * Just edit impl function
 * @copyright Copyright (c) 2025 jinho.choi
 * @see https://www.acmicpc.net/problem/1620
 * @license This code is for educational purposes only.
 */

#include <bits/stdc++.h>

using namespace std;

string str;

unordered_map<string, int> v;
string a[100001];

void impl() {
    int N, M;
    cin >> N >> M;

    for (int i = 0; i < N; i++) {
        cin >> str;
        v[str] = i + 1;
        a[i + 1] = str;
    }

    for (int i = 0; i < M; i++) {
        cin >> str;

        //* isdigit 함수는 문자열이 숫자인지 확인해주는 함수다.
        //* `atoi(s.c_str()) != 0`도 가능
        int num = atoi(str.c_str());

        if (num == 0) {
            //* 시간초과 방지를 위해 endl 대신 "\n" 사용.
            //* endl은 출력 버퍼를 비우는 작업이 있어 시간이 오래 걸린다.
            cout << v[str] << "\n";
        } else {
            cout << a[num] << "\n";
        }
    }
}

int main() {
    // This line is uncommented when starting process in local.
    // freopen("./questions/boj-1620.txt", "r", stdin);
    // for faster input/output
    ios_base::sync_with_stdio(false);cin.tie(NULL);cout.tie(NULL);

    impl();

    return 0;
}
